### ISSUE TITLE
Re Create Design Layout UI for v2 both Mobile and Web View

### ISSUE THREAD

**Issue by KevinCasoco** [KevinCasoco/waste-disposal-tracking-system#51]
- make it plain and simple
- make it responsive everything
- connect to our theme
- update all button and table

**Comment by KevinCasoco** [comment]
1st of January 2023 at least completed and working!!!!!

**Comment by KevinCasoco** [comment]
https://www.youtube.com/watch?v=HIDn_HpEuEQ

https://www.youtube.com/watch?v=HIDn_HpEuEQ

datatable responsive

**Comment by KevinCasoco** [comment]
![image](https://github.com/KevinCasoco/waste-disposal-tracking-system/assets/103113956/c942e1b6-a3e0-40ec-95b0-ed5e6032cdb0)

**Comment by jaytzy024** [comment]
di ko pa natapos to boi binibirada ko pa din tong mobile view ng table inaayos ko pa din update ako pag natapos ko na boi

**Comment by jaytzy024** [comment]
<img width="190" alt="image" src="https://github.com/KevinCasoco/waste-disposal-tracking-system/assets/135053221/59f4cd6c-54df-47f5-af23-80dcc83f54f6">
<img width="188" alt="image" src="https://github.com/KevinCasoco/waste-disposal-tracking-system/assets/135053221/a3cbd773-ee4a-443a-a7b6-d1e4f4419103">
